version: '3.9'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    env_file: ./backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        - SENTRY_RELEASE=${SENTRY_RELEASE:-unknown}
    ports:
      - "8080:8080"
    depends_on: [backend]
    restart: unless-stopped
