CREATE TABLE campaign_templates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  description TEXT NOT NULL,
  template_data JSONB NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  use_count INTEGER NOT NULL DEFAULT 0 CHECK (use_count >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS template_id UUID REFERENCES campaign_templates(id) ON DELETE SET NULL;
CREATE INDEX campaigns_template_id_idx ON campaigns(template_id) WHERE template_id IS NOT NULL;

INSERT INTO campaign_templates (slug, name, category, description, template_data) VALUES
('community-project', 'Community project', 'community', 'Bring neighbours together around a shared local goal.', '{"title":"Bring our community project to life","description":"What does your community need, who will benefit, and how will you keep supporters updated?","target_amount":"5000","milestones":[{"title":"Plan with the community","description":"Confirm partners, timeline, and final budget.","release_percentage":25},{"title":"Deliver the project","description":"Purchase materials and complete the planned work.","release_percentage":50},{"title":"Share the impact","description":"Publish outcomes and thank every supporter.","release_percentage":25}],"reward_tiers":[{"title":"Neighbour","description":"A heartfelt thank-you and project updates.","min_amount":"10","limit":"","estimated_delivery":""},{"title":"Community champion","description":"Recognition in the final community update.","min_amount":"50","limit":"","estimated_delivery":""}]}'),
('creative-work', 'Creative work', 'arts', 'Fund an album, film, book, exhibition, or other creative release.', '{"title":"Help us create something memorable","description":"Describe the work, your creative process, and what supporters will receive.","target_amount":"10000","milestones":[{"title":"Pre-production","description":"Finalize the concept, collaborators, and production plan.","release_percentage":30},{"title":"Create the work","description":"Produce, edit, and prepare the release.","release_percentage":50},{"title":"Release to supporters","description":"Deliver rewards and share the finished work.","release_percentage":20}],"reward_tiers":[{"title":"Early supporter","description":"Digital thank-you and behind-the-scenes updates.","min_amount":"10","limit":"","estimated_delivery":""},{"title":"First edition","description":"A signed or limited early edition.","min_amount":"50","limit":"100","estimated_delivery":""}]}'),
('startup', 'Startup', 'business', 'Validate and launch an early product with your first supporters.', '{"title":"Build the next version of our product","description":"Explain the problem, your solution, and how this funding unlocks the next milestone.","target_amount":"25000","milestones":[{"title":"Validate the solution","description":"Test the prototype with early users.","release_percentage":25},{"title":"Build the MVP","description":"Develop the core product experience.","release_percentage":50},{"title":"Launch to early adopters","description":"Onboard supporters and measure results.","release_percentage":25}],"reward_tiers":[{"title":"Early access","description":"Get access before the public launch.","min_amount":"25","limit":"","estimated_delivery":""},{"title":"Founding supporter","description":"Early access plus recognition as a founding supporter.","min_amount":"100","limit":"","estimated_delivery":""}]}'),
('charity', 'Charity', 'community', 'Make a clear, accountable case for a charitable cause.', '{"title":"Support a cause that matters","description":"Describe the need, the organization or people involved, and exactly how donations will be used.","target_amount":"10000","milestones":[{"title":"Prepare the program","description":"Confirm beneficiaries, partners, and purchasing plan.","release_percentage":30},{"title":"Deliver support","description":"Provide the promised resources or services.","release_percentage":50},{"title":"Report the impact","description":"Share receipts, outcomes, and stories from the program.","release_percentage":20}],"reward_tiers":[{"title":"Supporter","description":"A thank-you and impact update.","min_amount":"10","limit":"","estimated_delivery":""},{"title":"Impact partner","description":"A personal thank-you in the impact report.","min_amount":"100","limit":"","estimated_delivery":""}]}'),
('personal-cause', 'Personal cause', 'other', 'Share a personal need with clarity, dignity, and transparency.', '{"title":"Help us through this moment","description":"Share what happened, what support will cover, and how you will keep supporters informed.","target_amount":"5000","milestones":[{"title":"Address immediate needs","description":"Cover urgent costs and essential support.","release_percentage":60},{"title":"Stabilize and recover","description":"Fund the next steps toward recovery.","release_percentage":40}],"reward_tiers":[{"title":"With gratitude","description":"A personal thank-you and update.","min_amount":"10","limit":"","estimated_delivery":""}]}'),
('event', 'Event', 'community', 'Plan a memorable event and give attendees a clear reason to back it.', '{"title":"Make this event happen","description":"Describe the event, who it is for, and what the funding will make possible.","target_amount":"7500","milestones":[{"title":"Book the essentials","description":"Confirm venue, permits, and key suppliers.","release_percentage":40},{"title":"Produce the event","description":"Complete programming, materials, and promotion.","release_percentage":40},{"title":"Welcome attendees","description":"Run the event and share the highlights.","release_percentage":20}],"reward_tiers":[{"title":"Event supporter","description":"A thank-you and event update.","min_amount":"10","limit":"","estimated_delivery":""},{"title":"Early ticket","description":"One early-access event ticket.","min_amount":"35","limit":"100","estimated_delivery":""}]}')
ON CONFLICT (slug) DO NOTHING;
